version: '3.8'
services:
  ai-router:
    image: node:18-alpine
    container_name: logos-ai-router
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - PORT=3001
    command: sh -c "npm install && node src/index.js"
    networks:
      - logos-ai
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: logos-ai-cache
    ports:
      - "6379:6379"
    networks:
      - logos-ai
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

networks:
  logos-ai:
    driver: bridge

volumes:
  redis-data:
